---
title: "(Deters - Trump) Results"
author: Colleen Malloy
format: html
editor: visual
---

```{r}
library(readr)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(sf)
library(RColorBrewer
```

```{r}
results2020 <- read_excel("../data/election results/G20_Official_Canvass.xlsx",
                          sheet = "Candidates",skip=1)
map <- st_zm(st_read("../data/maps/precincts_2020.shp"))

mapANDresults2020 <-
  left_join(map, results2020, by = c("PRECINCT" = "PRECINCT"))


columns <- mapANDresults2020 %>%
  select(`PRC #`, `PRECINCT`, `REGISTERED VOTERS TOTAL`, `PERCENT`,  `Biden & Harris  (Dem)`, `Trump & Pence       (Rep)`,`Joseph T. Deters      (Rep)`, `Fanon A. Rucker      (Dem)`) %>% 
  mutate(Trump.prop = `Trump & Pence       (Rep)`/( `Biden & Harris  (Dem)`+ `Trump & Pence       (Rep)`)) %>% 
  mutate(Deters.prop = `Joseph T. Deters      (Rep)`/(`Joseph T. Deters      (Rep)` + `Fanon A. Rucker      (Dem)`)) %>% 
  mutate(prop.difference.Rep = Deters.prop - Trump.prop) %>% 
  mutate(vote.difference.Rep = (`Joseph T. Deters      (Rep)`) - (`Trump & Pence       (Rep)`))


columns%>%
  ggplot(aes(fill=prop.difference.Rep)) +
  geom_sf()+
  labs(title = "2020 (Deters minus Trump) Election Results", 
       subtitle = "",
       fill = "Vote for Deters - Trump (%)", 
       caption = "")+
  scale_fill_gradientn(colours=brewer.pal(n=10,name="PRGn"),na.value = "transparent",
                           breaks=c(-.05,0, .05, .1, .15, .2, .22),labels=c("-.05%", "0%", ".05%", "10%", "15", "20%", "22%"),
                           limits=c(-.05,.22))

```

```{r}
mapANDresults2020 %>% 
  mutate(Biden.prop = `Biden & Harris  (Dem)`/( `Biden & Harris  (Dem)`+ `Trump & Pence       (Rep)`)) %>%
  ggplot(aes(fill=Biden.prop)) +
  geom_sf()+
  labs(title = "2020 Presidential Election", 
       subtitle = "Joe Biden vs Donald Trump",
       fill = "Vote for \nBiden (%)", 
       caption = "")+
  scale_fill_gradientn(colours=brewer.pal(n=10,name="RdBu"),na.value = "transparent",
                           breaks=c(0,.25,0.5,.75,1),labels=c("0%","25%","50%","75%","100%"),
                           limits=c(0,1))

### find which precincts in our dataframe are the ones from Norwood and the ones from Hyde Park with grepl() command
###  ?grepl    - to see its help page



grepl('NORW',mapANDresults2020$PRECINCT)
norwood = st_union(mapANDresults2020[grepl('NORW',mapANDresults2020$PRECINCT),])

```
